version: "2"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false

plugins:
  sonar-python:
    enabled: true
    config:
      test_patterns:
        - "metpy/**/tests/*.py"
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true

exclude_patterns:
- "versioneer.py"
- "metpy/_version.py"
- "metpy/io/_nexrad_msgs/msg*.py"
- "docs/**/*"
