# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=${HOME}/miniconda/bin:$PATH
  - conda update --yes conda
  - python -V

install:
  - conda create --yes -n travis python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose
  - source activate travis
  - python setup.py install

script: nosetests -v
