# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

env:
  global:
    - DEPENDS="numpy matplotlib scipy"

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 2.7
      env: DEPENDS="numpy=1.8.0 matplotlib=1.4.0 scipy=0.13.3"
    - python: 2.7
      env: LINT=true
    # Docs built on 2.7 because that's what readthedocs uses
    - python: 2.7
      env: DOCBUILD=true
    - python: 3.2
    - python: 3.3
    - python: 3.4
      env: NOSE_WITH_COVERAGE=y NOSE_COVER_PACKAGE=metpy
    - python: 3.4
      env: LINT=true
    - python: nightly
  allow_failures:
    - python: 2.6, 3.2, nightly

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=${HOME}/miniconda/bin:$PATH
  - conda create --yes -n travis python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose flake8
  - source activate travis
  - if [[ $LINT == true ]]; then
      pip install pep8-naming;
    fi
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      pip install coveralls;
    fi
  # Stuck on sphinx 1.2 until readthedocs upgrades
  - if [[ $DOCBUILD == true ]]; then
      conda install --yes sphinx=1.2;
      pip install sphinxcontrib-napoleon;
    fi

install:
  - python setup.py install

script:
  - if [[ $LINT == true ]]; then
      flake8 metpy;
    elif [[ $DOCBUILD == true ]]; then
      cd docs;
      make html;
    else
      nosetests;
    fi

after_success:
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      coveralls;
    fi
