# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - python -V
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose
  - source activate env_name
  - python setup.py install
script: nosetests -v
