# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

addons:
  apt:
    packages:
    - libblas3gf
    - liblapack3gf

env:
  global:
    - REQUIRES=requirements.txt

matrix:
  include:
    - python: 2.7
    - python: 2.7
      env: REQUIRES=min-requirements.txt
    - python: 2.7
      env: LINT=true
    # Docs built on 2.7 because that's what readthedocs uses
    - python: 2.7
      env: DOCBUILD=true
    - python: 3.2
    - python: 3.3
    - python: 3.4
      env: NOSE_WITH_COVERAGE=y NOSE_COVER_PACKAGE=metpy
    - python: 3.4
      env: LINT=true
    #- python: nightly
  allow_failures:
    - python: nightly

before_install:
  # Stuck on sphinx 1.2 for docbuilds until readthedocs upgrades
  - virtualenv --python=python venv
  - source venv/bin/activate
  - if [[ $LINT == true ]]; then
      pip install flake8 pep8-naming;
    else
      if [[ $DOCBUILD == true ]]; then
        pip install sphinx==1.2;
        pip install sphinxcontrib-napoleon;
      else
        pip install nose;
      fi;
      wget https://github.com/MetPy/travis-wheels/archive/${TRAVIS_PYTHON_VERSION}.zip -O wheels.zip && unzip wheels.zip;
      if [[ $TRAVIS_PYTHON_VERSION == "nightly" ]]; then
        cd travis-wheels-${TRAVIS_PYTHON_VERSION}/wheel-0.24.0 && python setup.py install && cd ../..;
      fi;
      pip install -f "file://$PWD/travis-wheels-${TRAVIS_PYTHON_VERSION}/wheelhouse/" -r $REQUIRES;
      python -c "import numpy; print(numpy.__version__)";
    fi
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      pip install coveralls;
    fi

install:
  - if [[ $LINT != true ]]; then
      python setup.py install;
    fi

script:
  - if [[ $LINT == true ]]; then
      flake8 metpy;
    elif [[ $DOCBUILD == true ]]; then
      cd docs;
      make html;
    else
      nosetests;
    fi

after_success:
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      coveralls;
    fi
