# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: LINT=false
    - python: 3.3
      env: LINT=false
    - python: 3.4
      env: LINT=false
    - python: 3.4
      env: LINT=true

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=${HOME}/miniconda/bin:$PATH

install:
  - conda create --yes -n travis python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose flake8
  - source activate travis
  - python setup.py install

script:
  - if [[ $LINT == true ]]; then
      flake8 metpy;
    else
      nosetests;
    fi
