# Create full conda environment for development, including some useful tools
name: devel
channels:
  - https://conda.binstar.org/conda-forge
  - https://conda.binstar.org/scitools
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - pint
  - netcdf4
  - jupyter
  - sphinx
  - pytest
  - pytest-cov
  #- pytest-mpl
  #- pytest-runner
  - flake8
  - pep8-naming
  - pyproj
  - cartopy
  - jupyter_client!=4.2.1
