name: Build Docs

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  #
  # Build our docs on Linux against multiple Pythons
  #
  Docs:
    name: ${{ matrix.python-version }} ${{ matrix.dep-versions }}
    runs-on: ubuntu-20.04
    env:
      DOC_VERSION: dev
    environment:
      name: github-pages
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            check-links: false
            dep-versions: requirements.txt
          - python-version: 3.9
            check-links: true
            dep-versions: requirements.txt

    steps:
    # We check out only a limited depth and then pull tags to save time
    - name: Checkout source
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 100

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Add extras to requirements
      run: cat ci/extra_requirements.txt >> ci/doc_requirements.txt

    - name: Install using PyPI
      uses: ./.github/actions/install-pypi
      with:
        need-cartopy: true
        type: 'doc'
        python-version: ${{ matrix.dep-versions }}

    - name: Build docs
      uses: ./.github/actions/build-docs
      with:
        run-linkchecker: ${{ github.event_name == 'pull_request' && matrix.check-links == true }}
        upload-build: ${{ github.event_name == 'pull_request' }}
        key: ${{ runner.os }}-${{ matrix.python-version }}

    # This overrides the version "dev" with the proper version if we're building off a
    # branch that's not main (which is confined to n.nn.x above) or on a tag.
    - name: Set doc version
      if: ${{ github.event_name != 'push' || !contains(github.ref, 'main') }}
      run: echo "DOC_VERSION=v$(python -c 'import metpy,re; print(re.search(r"(\d+\.\d+)", metpy.__version__)[0])')" >> $GITHUB_ENV

    - name: Upload to GitHub Pages
      if: ${{ github.event_name != 'pull_request' && matrix.python-version == '3.9' }}
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.GHPAGES_DEPLOY_KEY }}
        publish_dir: ./docs/build/html
        exclude_assets: '.buildinfo,_static/jquery-*.js,_static/underscore-*.js'
        destination_dir: ./${{ env.DOC_VERSION }}
        keep_files: false
        full_commit_message: Deploy ${{ env.DOC_VERSION }} to GitHub Pages
