name: Build Docs (Conda)

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  pull_request:
    branches: [ main ]

jobs:
  #
  # Build our docs on macOS and Windows on Python 3.8 and 3.7, respectively.
  #
  Docs:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            os: macOS
          - python-version: 3.7
            os: Windows

    steps:
    # We check out only a limited depth and then pull tags to save time
    - name: Checkout source
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 100

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Install from Conda
      uses: ./.github/actions/install-conda
      with:
        type: 'doc'
        python-version: ${{ matrix.python-version }}

    - name: Build docs
      run: |
        export TEST_DATA_DIR=$GITHUB_WORKSPACE/staticdata
        pushd docs
        make overridecheck html O=-W
        popd

    - name: Upload docs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}-docs
        path: |
          docs/build/html
          !docs/_static/*.pdf
